#!/bin/sh
# Starts Emacs (through emacsclient) from an MSYS sh shell.
# Put this file in your MSYS sh:s PATH.
# (Created by Setup Helper at Fri Aug  2 09:27:13 2013)
"/c/bin/emacs-24.3/bin/emacsclient.exe" -n "$1"
